// Code generated by ifacemaker; DO NOT EDIT.

package authentication

import (
	_ "embed"
)

// Database ...
type Database interface {
	SetFileOperations(newOps FileInterface)
	LoadAuthDatabase(file string) (*AuthDatabase, error)
	CreateAuthDatabase(file string) (*AuthDatabase, error)
	CheckAuth(username string, password string) bool
	CheckUserExists(username string) bool
	GenerateNewSessionToken(username string) (string, error)
	CreateSessionToken(username string) string
	GetSessionToken(username string) (string, error)
	ValidateToken(session_token string) bool
	CheckSessionTime(session_token string) bool
	UpdateSession(session_token string, recently_accessed bool) error
	CreateUser(username string) error
	RemoveUser(username string) error
	LoginUser(username string, password string) (string, error)
	GetUserFromToken(session_token string) (string, error)
	Save() error
}
